//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClothesWebDBEntities : DbContext
    {
        public ClothesWebDBEntities()
            : base("name=ClothesWebDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoryTBL> categoryTBL { get; set; }
        public virtual DbSet<clientsTBL> clientsTBL { get; set; }
        public virtual DbSet<clothesTBL> clothesTBL { get; set; }
        public virtual DbSet<shopingDetailsTBL> shopingDetailsTBL { get; set; }
        public virtual DbSet<shopingsTBL> shopingsTBL { get; set; }
    }
}
