//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopingsTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shopingsTBL()
        {
            this.shopingDetailsTBL = new HashSet<shopingDetailsTBL>();
        }
    
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<System.DateTime> shoping_date { get; set; }
        public Nullable<decimal> sum_for_paying { get; set; }
    
        public virtual clientsTBL clientsTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shopingDetailsTBL> shopingDetailsTBL { get; set; }
    }
}
