//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopingDetailsTBL
    {
        public int id { get; set; }
        public Nullable<int> shoping_id { get; set; }
        public Nullable<int> cloth_id { get; set; }
        public Nullable<int> amount { get; set; }
    
        public virtual clothesTBL clothesTBL { get; set; }
        public virtual shopingsTBL shopingsTBL { get; set; }
    }
}
